export function classTemplate(params: {
  className: string
  actionSpaceCode: string
  obsSpaceCode: string
  resetBody: string
  stepBody: string
  httpsHeaders: string
}): string {
  const { className, actionSpaceCode, obsSpaceCode, resetBody, stepBody, httpsHeaders } = params
  return `# Auto-generated by 440hz NodeUI
# Do not edit manually — regenerate from the visual graph.

import gymnasium as gym
import numpy as np
import json
import os
import requests
from typing import Any

${httpsHeaders}


def _check_constraint(action: dict, rule: str) -> bool:
    """Stub: replace with your constraint logic or LLM call."""
    return True


def _rlaif_score(model: str, action: dict, state: dict, rubric: str, api_key_env: str) -> dict:
    """Stub: calls TEE-hosted overseer LLM to score the action."""
    return {"score": 0.0, "reasoning": "not implemented"}


def _call_mcp_tool(server_url: str, tool_name: str, action: dict, transport: str = "http") -> Any:
    """Stub: calls an external MCP tool server."""
    return {}


def _jsonpath_extract(data: dict, path: str) -> Any:
    """Stub: extracts a value using a JSONPath expression."""
    return None


class ${className}(gym.Env):
    """
    Generated Gymnasium environment: ${className}
    Created with 440hz NodeUI — https://440hz.dev
    """

    metadata: dict = {"render_modes": []}

    def __init__(self) -> None:
        super().__init__()
        self.action_space = ${actionSpaceCode}
        self.observation_space = ${obsSpaceCode}
        self.state: dict = {}

    def reset(self, seed: int | None = None, options: dict | None = None) -> tuple:
        super().reset(seed=seed)
        reward = 0.0
        observation = ""
        info: dict = {}
${resetBody}
        return observation, info

    def step(self, action: dict) -> tuple:
        reward = 0.0
        terminated = False
        truncated = False
        observation = str(self.state)
        info: dict = {}
${stepBody}
        return observation, reward, terminated, truncated, info

    def render(self) -> None:
        pass

    def close(self) -> None:
        pass
`
}
